// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	TcpConnectMapEvents           = "events"
	TcpConnectProgTraceTcpConnect = "trace_tcp_connect"
)

// LoadTcpConnect returns the embedded CollectionSpec for TcpConnect.
func LoadTcpConnect() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpConnectBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TcpConnect: %w", err)
	}

	return spec, err
}

// LoadTcpConnectObjects loads TcpConnect and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TcpConnectObjects
//	*TcpConnectPrograms
//	*TcpConnectMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTcpConnectObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTcpConnect()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TcpConnectSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpConnectSpecs struct {
	TcpConnectProgramSpecs
	TcpConnectMapSpecs
	TcpConnectVariableSpecs
}

// TcpConnectProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpConnectProgramSpecs struct {
	TraceTcpConnect *ebpf.ProgramSpec `ebpf:"trace_tcp_connect"`
}

// TcpConnectMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpConnectMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// TcpConnectVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpConnectVariableSpecs struct {
}

// TcpConnectObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTcpConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpConnectObjects struct {
	TcpConnectPrograms
	TcpConnectMaps
	TcpConnectVariables
}

func (o *TcpConnectObjects) Close() error {
	return _TcpConnectClose(
		&o.TcpConnectPrograms,
		&o.TcpConnectMaps,
	)
}

// TcpConnectMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTcpConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpConnectMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *TcpConnectMaps) Close() error {
	return _TcpConnectClose(
		m.Events,
	)
}

// TcpConnectVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTcpConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpConnectVariables struct {
}

// TcpConnectPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTcpConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpConnectPrograms struct {
	TraceTcpConnect *ebpf.Program `ebpf:"trace_tcp_connect"`
}

func (p *TcpConnectPrograms) Close() error {
	return _TcpConnectClose(
		p.TraceTcpConnect,
	)
}

func _TcpConnectClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcpconnect_bpfeb.o
var _TcpConnectBytes []byte
