// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type TcpTrackerConnKey struct {
	_     structs.HostLayout
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
}

type TcpTrackerConnStats struct {
	_         structs.HostLayout
	TxBytes   uint64
	RxBytes   uint64
	TxPackets uint64
	RxPackets uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	TcpTrackerMapConnStatsMap     = "conn_stats_map"
	TcpTrackerMapEvents           = "events"
	TcpTrackerProgTraceTcpConnect = "trace_tcp_connect"
	TcpTrackerProgTraceTcpRecvmsg = "trace_tcp_recvmsg"
	TcpTrackerProgTraceTcpSendmsg = "trace_tcp_sendmsg"
)

// LoadTcpTracker returns the embedded CollectionSpec for TcpTracker.
func LoadTcpTracker() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpTrackerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TcpTracker: %w", err)
	}

	return spec, err
}

// LoadTcpTrackerObjects loads TcpTracker and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TcpTrackerObjects
//	*TcpTrackerPrograms
//	*TcpTrackerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTcpTrackerObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTcpTracker()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TcpTrackerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpTrackerSpecs struct {
	TcpTrackerProgramSpecs
	TcpTrackerMapSpecs
	TcpTrackerVariableSpecs
}

// TcpTrackerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpTrackerProgramSpecs struct {
	TraceTcpConnect *ebpf.ProgramSpec `ebpf:"trace_tcp_connect"`
	TraceTcpRecvmsg *ebpf.ProgramSpec `ebpf:"trace_tcp_recvmsg"`
	TraceTcpSendmsg *ebpf.ProgramSpec `ebpf:"trace_tcp_sendmsg"`
}

// TcpTrackerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpTrackerMapSpecs struct {
	ConnStatsMap *ebpf.MapSpec `ebpf:"conn_stats_map"`
	Events       *ebpf.MapSpec `ebpf:"events"`
}

// TcpTrackerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcpTrackerVariableSpecs struct {
}

// TcpTrackerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTcpTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpTrackerObjects struct {
	TcpTrackerPrograms
	TcpTrackerMaps
	TcpTrackerVariables
}

func (o *TcpTrackerObjects) Close() error {
	return _TcpTrackerClose(
		&o.TcpTrackerPrograms,
		&o.TcpTrackerMaps,
	)
}

// TcpTrackerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTcpTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpTrackerMaps struct {
	ConnStatsMap *ebpf.Map `ebpf:"conn_stats_map"`
	Events       *ebpf.Map `ebpf:"events"`
}

func (m *TcpTrackerMaps) Close() error {
	return _TcpTrackerClose(
		m.ConnStatsMap,
		m.Events,
	)
}

// TcpTrackerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTcpTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpTrackerVariables struct {
}

// TcpTrackerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTcpTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcpTrackerPrograms struct {
	TraceTcpConnect *ebpf.Program `ebpf:"trace_tcp_connect"`
	TraceTcpRecvmsg *ebpf.Program `ebpf:"trace_tcp_recvmsg"`
	TraceTcpSendmsg *ebpf.Program `ebpf:"trace_tcp_sendmsg"`
}

func (p *TcpTrackerPrograms) Close() error {
	return _TcpTrackerClose(
		p.TraceTcpConnect,
		p.TraceTcpRecvmsg,
		p.TraceTcpSendmsg,
	)
}

func _TcpTrackerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcptracker_bpfeb.o
var _TcpTrackerBytes []byte
